server.port=8081
app.frontend-origin=http://localhost:5173

spring.datasource.url=jdbc:postgresql://localhost:5432/admin_panel_dev
spring.datasource.username=admin_panel_user
spring.datasource.password=admin_panel_password
spring.datasource.driver-class-name=org.postgresql.Driver
